# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

template: !include templates.yaml

eto_test:
  - name: side
    temp_min: 'sensor.pi07_temp_drive_min'
    temp_max: 'sensor.pi07_temp_drive_max'
  - name: back
    temp_min: 'sensor.pi07_temp_drive_min'
    temp_max: 'sensor.pi07_temp_drive_max'


# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.eto_test: debug
