# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

eto_test:
  - name: side
    scan_interval: 10
  - name: back
    scan_interval: 15


# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.eto_test: debug
